### ISSUE TITLE
Overlap x-axis in rplot, can you move labels to vertical

### ISSUE THREAD

**Issue by mwilson19** [tidymodels/corrr#108]
Not sure if exists or not, didn't see option but can we rotate the x-axis labels to be vertical so there is not overlap when there are a lot of features?  Thanks.

Comes up running titanic data set

```
library(corrr)
housing_cor <- housing_train %>% 
                  select(where(is.numeric)) %>% 
                  correlate() %>% 
                  rearrange() %>% 
                  shave()
#head(fashion(housing_cor))

rplot(housing_cor, print_cor = TRUE, shape = 20, colors = c(pal[1:2]))
```

**Comment by juliasilge** [comment]
The object created by `rplot()` is a ggplot2 object, so you can act on it in most of the ways you would act on any ggplot2 object, including changing it via calls to `theme()`:

``` r
library(corrr)
library(tidyverse)

x <- mtcars %>%
  correlate() %>% 
  focus(-cyl, -vs, mirror = TRUE) %>% 
  rearrange() %>% 
  shave()
#> 
#> Correlation method: 'pearson'
#> Missing treated using: 'pairwise.complete.obs'
#> Registered S3 method overwritten by 'seriation':
#>   method         from 
#>   reorder.hclust gclus

rplot(x)
#> Don't know how to automatically pick scale for object of type noquote. Defaulting to continuous.
```

![](https://i.imgur.com/b60Vgex.png)

``` r

rplot(x) +
  theme_gray()
#> Don't know how to automatically pick scale for object of type noquote. Defaulting to continuous.
```

![](https://i.imgur.com/vQEj76H.png)

``` r

rplot(x) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
#> Don't know how to automatically pick scale for object of type noquote. Defaulting to continuous.
```

![](https://i.imgur.com/7LwIJTo.png)

<sup>Created on 2020-07-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by mwilson19** [comment]
Thank you Julia, you are amazing and have helped me a lot...duh on the above!

**Comment by juliasilge** [comment]
Oh, it's probably not obvious until you see it in action!
