### ISSUE TITLE
variable instead of rowname

### ISSUE THREAD

**Issue by bjornerstedt** [tidymodels/corrr#117]
## Feature

The correlate functions generates a tibble with "rowname" as the first column. It should be called "variable" (or something similar) instead, to better match the the column content and to avoid having to rename the column when used in printed output.

**Comment by juliasilge** [comment]
This is... a great point. We've decided that our preferred name for the first column is `term`, like the [output from `broom::tidy()`](https://www.tidymodels.org/learn/develop/broom/#glossary).

It is possible that this change will break folks' existing code, so our plan from here is to start out by keeping the column name the _same_ and generating a [soft deprecation warning](https://lifecycle.r-lib.org/) that the name will change in the _future_. Then, in another release, we'll change the column name, still with a warning.

**Comment by bjornerstedt** [comment]
Calling it term is better, I agree.
