### ISSUE TITLE
Correlate is incorrect with numeric vectors as x,y

### ISSUE THREAD

**Issue by antoine-sachet** [tidymodels/corrr#120]
## Problem

`correlate` does not work at all when x and y are numeric vectors.

I am assuming it _should_ work because the doc for correlate says:

```
x	a numeric vector, matrix or data frame.
y	NULL (default) or a vector, matrix or data frame with compatible dimensions to x. The default is equivalent to y = x (but more efficient).
```

However, I realise more and more that the whole package pretty much assumes x is a data.frame. Maybe the doc should be updated to reflect that `x` should be a data.frame and remove the now useless `y` argument? It is ok if correlate only works with data.frames and is not a drop-in replacement for `cor` in all situations. It would be much clearer IMO.

## Reproducible example

A simple correlation between 2 vectors returns a 1x1 correlation matrix, with a single element which happens to be diagonal.
The correlation will take the value of the `diagonal` argument.

You won't be able to reproduce yet due to #119 (which I fixed in my fork) but you get the gist:

``` r
corrr::correlate(x = 1:10, y = 10:1, quiet = T)
#> # A tibble: 1 x 2
#>   rowname     x
#>   <chr>   <dbl>
#> 1 x          NA
corrr::correlate(x = 1:10, y = 10:1, diagonal = 0.66, quiet = T)
#> # A tibble: 1 x 2
#>   rowname     x
#>   <chr>   <dbl>
#> 1 x        0.66
```

<sup>Created on 2020-10-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by antoine-sachet** [comment]
The same bug appears when using a data.frame with only 1 column. That's a higher impact bug actually.

``` r
corrr::correlate(mtcars["cyl"])
#> 
#> Correlation method: 'pearson'
#> Missing treated using: 'pairwise.complete.obs'
#> # A tibble: 1 x 2
#>   rowname   cyl
#>   <chr>   <dbl>
#> 1 cyl        NA
```

<sup>Created on 2020-10-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thisisdaryn** [comment]
> However, I realise more and more that the whole package pretty much assumes x is a data.frame. Maybe the doc should be updated to reflect that `x` should be a data.frame and remove the now useless `y` argument? It is ok if correlate only works with data.frames and is not a drop-in replacement for `cor` in all situations. It would be much clearer IMO.

Yes, this is something that needs to be resolved. I will submit a PR when there is a decision. 

The original package author [commented here on the usage of the `y` argument](https://github.com/tidymodels/corrr/issues/115#issuecomment-680681583) in response to a previous issue. As is pointed out there, removing `y` would be a breaking change. 

I agree that the use of `y` was not among the common expected use cases and, additionally, is seemingly very rarely used.
