### ISSUE TITLE
corrr 0.4.3 blog post

### ISSUE THREAD

**Issue by topepo** [tidymodels/corrr#126]
I've started a branch in the [`tidyverse.org` repo](https://github.com/tidyverse/tidyverse.org/tree/corrr-0-4-3) for a `corrr` blog post. @thisisdaryn can you fill in the parts with new features and @jameslairdsmith can you add a section on the new function you had in #116? 

The process is to install `remotes::install_github("r-lib/hugodown")` then `hugodown::hugo_install()`. You can edit the `index.Rmd` file in `tidyverse.org/content/blog/corrr-0-4-3`  then knit to md. 

@thisisdaryn can pick the art. Make a square image from the image that you use (credit the author in the yaml) and a wide image that is 5x wider than tall (it has to be exact). Name those `thumbnail-sq.jpg` and `thumbnail-wd.jpg` then run `hugodown::use_tidy_thumbnails()` to resize them.

**Comment by jameslairdsmith** [comment]
Thanks @topepo! PR adding my section is in tidyverse/tidyverse.org#487 .

**Comment by juliasilge** [comment]
[Published now](https://www.tidyverse.org/blog/2020/12/corrr-0-4-3/)! ✅
