### ISSUE TITLE
network_plot  ajust the width of lines and size of text

### ISSUE THREAD

**Issue by DrZhaoJie** [tidymodels/corrr#128]
![image](https://user-images.githubusercontent.com/55881098/103209278-a715f980-493d-11eb-967a-bb2cdf50004e.png)
Hi, I really enjoy your package and I had some questions about the network_plot function. How can I adjust the size of the text (names of the node, such as "gear", "am", "qsec") and the width of the connecting line?  I would appreciate it if you could give me a help. Thank you very much!

**Comment by juliasilge** [comment]
We don't currently have support have changing these aspects of the plot. You may already have checked this out, but you can see the [arguments to `network_plot()` here](https://corrr.tidymodels.org/reference/network_plot.html), which allow to change certain characteristics of the plot, but not the width of the lines or the size of the text.

If you are trying to change some scaling overall (like "the text is too big") you could change the size of the _plot itself_ to make room. If you have some other kind of use case, please share more and we can prioritize this feature request! 🙌

**Comment by juliasilge** [comment]
Let us know if you have further questions!
