### ISSUE TITLE
network_plot font type

### ISSUE THREAD

**Issue by famfigueiredo** [tidymodels/corrr#136]
I apologize if it is a stupid question, but is it possible to change fonts in network_plot geom labels?

**Comment by juliasilge** [comment]
This is _not_ a stupid question, and I find this quite frustrating myself when it comes to `autoplot()`-ish methods, as a user of custom fonts. There was supposedly some work being planned in ggplot2 that will make it easier to theme fonts like this, but in the meantime, what I do if I really want to customize fonts is:

- copy the source code of the function I am using into my script, usually in the `setup` chunk of my `.Rmd`
- change the thing I want to change, like the [font being used by ggrepel](https://github.com/tidymodels/corrr/blob/master/R/cor_df.R#L278-L282)
- go about my way

This is far from ideal, we know. 😒

**Comment by famfigueiredo** [comment]
That is brilliant, @juliasilge. Thank you so much for the explanation.
My R proficiency is only average, but I was (almost) sure this was possible and I had unsuccessfully tried finding the `network_plot` code source.

Even though it is not ideal, I can really use this newfound knowledge.
Issue solved on my part!
