### ISSUE TITLE
Output correlation table with significance markers

### ISSUE THREAD

**Issue by AlarithUhde** [tidymodels/corrr#137]
## Feature Request

In scientific papers we often find correlation tables of all measures used in a study, with markers for significance levels. They are helpful to get an overview about the overall structure of the data. I found producing such a table automatically in R surprisingly difficult. An example could look like this:

https://www.researchgate.net/figure/Correlation-matrix-of-publications-by-programs-across-major-behavior-analytic-journals_tbl1_275652409

I am aware that the corr.test() function in the psych package reports p-values, but they are in a different table which makes it hard to read and re-integrate later. A related feature request (https://github.com/tidymodels/corrr/issues/29) was closed several years ago, but rather than a colored graph I would prefer a feature to output a table. I imagine the workflow like this:

```r
library(tidyverse)
library(corrr)

df %>%
  correlate() %>%
  shave() %>%
  fashion(significance_marker="asterisk")
```

The marker itself could be flexible. Asterisks are most common to my knowledge, but sometimes letters (a, b, c; i, ii, iii) or bold text are used as well.

Alternatives I have tried:

- cor(); no integrated reporting of significance levels
- rcor() from the Hmisc package; someone has actually written a script for this, but it would be great if a simple option could be integrated in corrr: https://paulvanderlaken.com/2020/07/28/publication-ready-correlation-matrix-significance-r/
- corr.test() from the psych package; correlations and significance levels are split in two tables, making it hard to read
- correlate() from the lsr package, but it also doesn't show significance levels and masks the correlate() function. It is described here: https://psyteachr.github.io/msc-conv-f2f/rm2-r-markdown-correlations.html#pre-class-activities-1

**Comment by juliasilge** [comment]
It's possible to build a table like this using the new-ish functionality in [`colpair_map()`](https://corrr.tidymodels.org/reference/colpair_map.html):

``` r
library(tidyverse)
library(corrr)

calc_p_value <- function(vec_a, vec_b, sig_level){
  test_res <- cor.test(vec_a, vec_b)
  sig <- if_else(test_res$p.value < sig_level, "*", "")
  paste0(round(cor.test(vec_a, vec_b)$estimate, 2), sig)
}

colpair_map(mtcars, calc_p_value, 0.05) %>%
  shave()
#> # A tibble: 11 x 12
#>    term  mpg    cyl    disp   hp     drat   wt     qsec  vs    am    gear  carb 
#>    <chr> <chr>  <chr>  <chr>  <chr>  <chr>  <chr>  <chr> <chr> <chr> <chr> <chr>
#>  1 mpg   <NA>   <NA>   <NA>   <NA>   <NA>   <NA>   <NA>  <NA>  <NA>  <NA>  <NA> 
#>  2 cyl   -0.85* <NA>   <NA>   <NA>   <NA>   <NA>   <NA>  <NA>  <NA>  <NA>  <NA> 
#>  3 disp  -0.85* 0.9*   <NA>   <NA>   <NA>   <NA>   <NA>  <NA>  <NA>  <NA>  <NA> 
#>  4 hp    -0.78* 0.83*  0.79*  <NA>   <NA>   <NA>   <NA>  <NA>  <NA>  <NA>  <NA> 
#>  5 drat  0.68*  -0.7*  -0.71* -0.45* <NA>   <NA>   <NA>  <NA>  <NA>  <NA>  <NA> 
#>  6 wt    -0.87* 0.78*  0.89*  0.66*  -0.71* <NA>   <NA>  <NA>  <NA>  <NA>  <NA> 
#>  7 qsec  0.42*  -0.59* -0.43* -0.71* 0.09   -0.17  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  8 vs    0.66*  -0.81* -0.71* -0.72* 0.44*  -0.55* 0.74* <NA>  <NA>  <NA>  <NA> 
#>  9 am    0.6*   -0.52* -0.59* -0.24  0.71*  -0.69* -0.23 0.17  <NA>  <NA>  <NA> 
#> 10 gear  0.48*  -0.49* -0.56* -0.13  0.7*   -0.58* -0.21 0.21  0.79* <NA>  <NA> 
#> 11 carb  -0.55* 0.53*  0.39*  0.75*  -0.09  0.43*  -0.6… -0.5… 0.06  0.27  <NA>

colpair_map(mtcars, calc_p_value, 0.05) %>%
  shave() %>%
  mutate_all(replace_na, "") %>%
  knitr::kable()
```

| term | mpg     | cyl     | disp    | hp      | drat    | wt      | qsec    | vs      | am     | gear | carb |
|:-----|:--------|:--------|:--------|:--------|:--------|:--------|:--------|:--------|:-------|:-----|:-----|
| mpg  |         |         |         |         |         |         |         |         |        |      |      |
| cyl  | -0.85\* |         |         |         |         |         |         |         |        |      |      |
| disp | -0.85\* | 0.9\*   |         |         |         |         |         |         |        |      |      |
| hp   | -0.78\* | 0.83\*  | 0.79\*  |         |         |         |         |         |        |      |      |
| drat | 0.68\*  | -0.7\*  | -0.71\* | -0.45\* |         |         |         |         |        |      |      |
| wt   | -0.87\* | 0.78\*  | 0.89\*  | 0.66\*  | -0.71\* |         |         |         |        |      |      |
| qsec | 0.42\*  | -0.59\* | -0.43\* | -0.71\* | 0.09    | -0.17   |         |         |        |      |      |
| vs   | 0.66\*  | -0.81\* | -0.71\* | -0.72\* | 0.44\*  | -0.55\* | 0.74\*  |         |        |      |      |
| am   | 0.6\*   | -0.52\* | -0.59\* | -0.24   | 0.71\*  | -0.69\* | -0.23   | 0.17    |        |      |      |
| gear | 0.48\*  | -0.49\* | -0.56\* | -0.13   | 0.7\*   | -0.58\* | -0.21   | 0.21    | 0.79\* |      |      |
| carb | -0.55\* | 0.53\*  | 0.39\*  | 0.75\*  | -0.09   | 0.43\*  | -0.66\* | -0.57\* | 0.06   | 0.27 |      |

<sup>Created on 2021-04-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

You can customize the function `calc_p_value()` to make the table however you like.

**Comment by juliasilge** [comment]
I don't think it's likely that we will build out functionality for pre-built tables in the corrr package itself, since people have such individual needs for reporting.

**Comment by AlarithUhde** [comment]
Thank you, your solution was quite helpful for my case.

**Comment by juliasilge** [comment]
Great to hear that @AlarithUhde! 🙌
