### ISSUE TITLE
Network Plot doesn't depict edges

### ISSUE THREAD

**Issue by thomasjwood** [tidymodels/corrr#148]
```
library(tidyverse)
library(corrr)

mtcars %>% 
  correlate %>% 
  network_plot
```

returns

![image](https://user-images.githubusercontent.com/1422023/136594182-77aba321-5554-4f8b-ac39-1fa63a2c8fea.png)

How do I include the curved edges?

**Comment by juliasilge** [comment]
No problem at all! 🙌
