### ISSUE TITLE
Add documentation for 'use'

### ISSUE THREAD

**Issue by joelnitta** [tidymodels/corrr#150]
Not sure if this is a "feature request" or a "bug".

I couldn't find any documentation on the values for the `use` argument of `correlate()` (`"everything"`, `"all.obs"`, `"complete.obs"`, `"na.or.complete"`, or `"pairwise.complete.obs"`).

The current help file for `correlate()` only says
> use: an optional character string giving a method for computing covariances in the presence of missing values. This must be (an abbreviation of) one of the strings "everything", "all.obs", "complete.obs", "na.or.complete", or "pairwise.complete.obs".

without any explanation of what each of those settings does.

corrr v0.4.3

**Comment by joelnitta** [comment]
Follow-up: I found the "missing" documentation [in the help file for `stats::cor()`](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/cor). Still, it's not a given that `corrr::correlate()` behaves exactly the same, and I think it would be more user-friendly if documented in `corrr::correlate()` as well, or if at least more explicit guidance was provided about where to look.

**Comment by juliasilge** [comment]
We use `@inheritParams stats::cor` and I think that's still the right thing to do but we could add more info in `@details` the way that `stats::cor()` does.

Side note: [the `\itemize()` list](https://github.com/tidymodels/corrr/blob/8d76ea66b07770e29435a4b0758e6e7eb5c4e7df/R/correlate.R#L7) is set up wrong so [we don't see the intro](https://corrr.tidymodels.org/reference/correlate.html).

**Comment by thisisdaryn** [comment]
I will add the additional info in @details.

**Comment by thisisdaryn** [comment]
Closed in #151
