### ISSUE TITLE
Limit color bar range in network_plot()

### ISSUE THREAD

**Issue by john-s-f** [tidymodels/corrr#158]
## Feature

Previously, there was an issue ticket #27, where manual limiting of the range of the `network_plot` function was discussed. I believe this would be a useful feature. Consider the situation where the dataset only produces positive correlation values. In the first plot, half of the color range is useless.
``` r
library(tidyverse)
library(corrr)

mtcars |>
  select(cyl, disp, hp, wt, carb) |> 
  correlate() |>
  network_plot()
#> 
#> Correlation method: 'pearson'
#> Missing treated using: 'pairwise.complete.obs'
```

![](https://i.imgur.com/kToLOGL.png)

You can sort of circumvent this in a hacky way by making the color scale as so, but that's confusing to the reader because there are no correlations below 0  so why is it shown and even if there were, it'd all show as black so you couldn't tell what it was anyway. The goal here was to emulate if the scale started at 0 and went to 1.
``` r
mtcars |> 
  select(cyl, disp, hp, wt, carb) |>
  correlate() |>
  network_plot(colors = c("black", "black", "skyblue"))
#> 
#> Correlation method: 'pearson'
#> Missing treated using: 'pairwise.complete.obs'
```

![](https://i.imgur.com/RbLZ0vN.png)

<sup>Created on 2022-04-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Regarding 

> the user chooses to show moderate correlations while ignoring weak and strong relationships. 

IMO, the software should allow people to do what they want, it's their job not to do something wrong, not the softwares. 

>As a viewer of the plot, it seems weird that a plot might show correlations between 0.3 and 0.6 and then it would be left to the viewer to reason or guess whether the missing relationships are weaker (i.e.< 0.3) or stronger (i.e. >0.6) than the relationships shown.

If a plot shows a particular range of data, for example, between 0.3 and 0.6, why should the reader assume that data is being hidden as opposed to that being the true range of the data?

**Comment by juliasilge** [comment]
Thanks for your thoughts @john-s-f! Overall we definitely aim to build software that can keep folks from making common mistakes (we see this as part of the software's job), but we are happy to reevaluate this decision. Can you tell us a little more about how you have run into this as a problem in your use case?

**Comment by john-s-f** [comment]
It's situations where data only produce correlations of one sign, as in the above mtcars example. In my case, RNAseq datasets. These are datasets about gene expression and while it's not impossible to get negative correlations, it's highly unlikely in most use cases. Moreover, these datasets are generally highly correlated with each other (for example, between biological replicates in an experiment, or even between two treatment groups) so the entire -1 to 1 color scale makes it hard to display smaller differences. These kinds of correlation analyses are usually a sanity check that your data is ok and/or the start of other kinds of analyses. This plot in particular is helpful in showing people how their data groups and relates to other data they have, for example, a 3 replicates of a control group and 3 replicates each of two different treatments.

**Comment by thisisdaryn** [comment]
Hi @john-s-f,

I think the way to address your situation is to give the user the option to map the color gradient to the range, i.e. min to max, of correlations in the `cor_df` object - as opposed to mapping it -1 to 1 (which will remain the default). 

I will submit a PR soon implementing this via using the pre-existing `legend` argument, which could then be toggled between the options.  

I'm generally skeptical about adding an independent capability to manipulate the range arbitrarily. So I think this is the way to go.

**Comment by john-s-f** [comment]
Thanks, this is also a viable solution.

**Comment by juliasilge** [comment]
The solution here (using `legend = c("full", "range", "none")`) is now merged in. Let us know if you have further issues! 🙌
