### ISSUE TITLE
Question about network_plot function (corrr package)

### ISSUE THREAD

**Issue by jagodap** [tidymodels/corrr#161]
I recently found out about corrr and the network_plot function in it. I plotted some data I am working on and I  got really excited by how much theoretical  sense they made. I am working on a paper right now and I would really like include these plots. The problem is that the documentation mentions no references regarding  the algorithm/calculation used to display variables' proximity. In the package manual multidimensional clustering is mentioned, but not much else.

Does anybody have any know anything about hits

 Best regards

**Comment by juliasilge** [comment]
You can check out the [code used to make this plot here](https://github.com/tidymodels/corrr/blob/main/R/cor_df.R#L179). 

Briefly, the two-dimensional points are created with multidimensional scaling via `stats::cmdscale(distance, k = 2)` where `distance` is `1 - abs(your_correlation_dataframe)`.

**Comment by jagodap** [comment]
Thank you very much!!!!
