### ISSUE TITLE
`group_by_factors`

### ISSUE THREAD

**Issue by drsimonj** [tidymodels/corrr#22]
`group_by_factors` could be a boolean argument added to `correlate()`. If `group_by_factors == TRUE`, then `correlate()` is run separately for each grouping created by any factor variables present in the data set. Basically, it's a shorthand function to implement the `tidyr::nest()` method described [here](https://drsimonj.svbtle.com/running-a-model-on-separate-groups).

Few notes for implementing:
- If `TRUE`, Would return a grouped data frame. Will need ways to apply other corrr functions to such an object.
- By default (`group_by_factors == FALSE`), `correlate()` will need to `keep()` only numeric variables. This is a good idea anyway. If any variables (factors, character, etc) are dropped, this should be printed out as a `warning`. When `group_by_factors == TRUE`, non-numeric variables are used by `nest()` first, leaving only numeric for the correlations.

Conceived after [this tweet](https://twitter.com/nathanweastwood/status/779038915147825153).

**Comment by drsimonj** [comment]
Issue has been open for almost 3 years, so will close. Grouping can be done with tidyverse (e.g., use of tidyr's `nest()`) as described in the linked tweet above.

**Comment by burgerga** [comment]
Can you reopen? I think something like this is still very useful!

Here some reprexes as requested in https://community.rstudio.com/t/how-to-apply-corrr-correlate-by-group/6236

I would LOVE to have 
``` r
library(tidyverse)
library(corrr)
group_by(iris, Species) %>%
  correlate()
#> Error in stats::cor(x = x, y = y, use = use, method = method): 'x' must be numeric
```

<sup>Created on 2021-02-18 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

have the same output as 

``` r
library(tidyverse)
library(corrr)
group_by(iris) %>%
  nest_by(Species) %>%
  summarise(correlate(data, quiet = T))
#> `summarise()` has grouped output by 'Species'. You can override using the `.groups` argument.
#> # A tibble: 12 x 6
#> # Groups:   Species [3]
#>    Species    term         Sepal.Length Sepal.Width Petal.Length Petal.Width
#>    <fct>      <chr>               <dbl>       <dbl>        <dbl>       <dbl>
#>  1 setosa     Sepal.Length       NA           0.743        0.267       0.278
#>  2 setosa     Sepal.Width         0.743      NA            0.178       0.233
#>  3 setosa     Petal.Length        0.267       0.178       NA           0.332
#>  4 setosa     Petal.Width         0.278       0.233        0.332      NA    
#>  5 versicolor Sepal.Length       NA           0.526        0.754       0.546
#>  6 versicolor Sepal.Width         0.526      NA            0.561       0.664
#>  7 versicolor Petal.Length        0.754       0.561       NA           0.787
#>  8 versicolor Petal.Width         0.546       0.664        0.787      NA    
#>  9 virginica  Sepal.Length       NA           0.457        0.864       0.281
#> 10 virginica  Sepal.Width         0.457      NA            0.401       0.538
#> 11 virginica  Petal.Length        0.864       0.401       NA           0.322
#> 12 virginica  Petal.Width         0.281       0.538        0.322      NA
```

<sup>Created on 2021-02-18 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>


And of course it would be a shame if pandas can do it, but not R 😛 

``` r
library(reticulate)
pd = import('pandas', convert = F)
iris_pd = pd$DataFrame(dict(iris))
iris_pd$groupby('Species')$corr()
#>                          Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
#> Species                                                                      
#> setosa     Sepal.Length      1.000000     0.742547      0.267176     0.278098
#>            Sepal.Width       0.742547     1.000000      0.177700     0.232752
#>            Petal.Length      0.267176     0.177700      1.000000     0.331630
#>            Petal.Width       0.278098     0.232752      0.331630     1.000000
#> versicolor Sepal.Length      1.000000     0.525911      0.754049     0.546461
#>            Sepal.Width       0.525911     1.000000      0.560522     0.663999
#>            Petal.Length      0.754049     0.560522      1.000000     0.786668
#>            Petal.Width       0.546461     0.663999      0.786668     1.000000
#> virginica  Sepal.Length      1.000000     0.457228      0.864225     0.281108
#>            Sepal.Width       0.457228     1.000000      0.401045     0.537728
#>            Petal.Length      0.864225     0.401045      1.000000     0.322108
#>            Petal.Width       0.281108     0.537728      0.322108     1.000000
```

<sup>Created on 2021-02-18 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by juliasilge** [comment]
We are happy to track interest in this to prioritize development, but the current solution with `nest_by()` solves the problem nicely. 👍

**Comment by burgerga** [comment]
Thanks for your quick response! Personally, I can live with the `nest_by()` solution, but I am also teaching R and nested data is quite an advanced topic for some, so hopefully the `group_by` option will also be available someday :)
