### ISSUE TITLE
Manually adjust correlation limits in plots

### ISSUE THREAD

**Issue by drsimonj** [tidymodels/corrr#27]
Currently, network_plot() and rplot() limit the colours and alpha etc to -1 and 1. However, with the addition of operations, these limits can be escaped.

Furthermore, it might just be nice for users to adjust these limits to suit their own purpose.

Thanks to @jcberny for the suggestion.

**Comment by thisisdaryn** [comment]
Hi,

Do you have an example use case? 

If I understand correctly, the suggestion is to allow the user to show a range of correlations other than -1 to 1. I think that the issue of allowing users to change how the color scales are applied to the displayed values is interesting. I have questions about allowing users to choose the range of correlations to display. 

My intuition is that removing the weakest correlations is the most useful use case of giving the user to a broad ability to choose the correlation limits. `network_plot` currently allows for small correlations to be removed from the plot using its _min_cor_ argument. `rplot` can be potentially be made to do the same. `rplot` naturally de-emphasizes the smallest correlations.
Adding this feature would necessitate reconciling the new feature with the existing feature. 

I think there's one problematic scenario in particular with user-supplied limits: the user chooses to show moderate correlations while ignoring weak and strong relationships. As a viewer of the plot, it seems weird that a plot might show correlations between 0.3 and 0.6 and then it would be left to the viewer to reason or guess  whether the missing relationships are weaker (i.e.< 0.3) or stronger (i.e. >0.6) than the relationships shown. 

-daryn

**Comment by juliasilge** [comment]
Those are great points, @thisisdaryn. Let's close this issue and leave the plot limits as they are for now. We can revisit this issue in the future if users open new issues asking about this.
