### ISSUE TITLE
p-values with p.adjust corrections

### ISSUE THREAD

**Issue by BobMuenchen** [tidymodels/corrr#29]
The bigger the correlation matrix, the greater the chance that many of the correlations that make such a pretty pattern don't differ significantly from zero. It would be nice to see just a matrix of p-values, and as color-coding to the correlations themselves. Thanks for considering it!

**Comment by drsimonj** [comment]
Thanks, Bob!

p-values are a topic that have come up a lot. If I find the time, I'll try to incorporate a function in corrr to handle this directly.

In the meantime, you have some nice options in other packages (just mentioning for anyone else who comes across this):

- `RcmdrMisc::rcorr.adjust()`
- `psych::corr.test()`

After using these, you can make use of the new function, `as_cordf()` (available in dev version only). If you have a matrix, even of p-values, use `as_cordf()` to transform it to corrr's correlation data frame format, which you can then feed into any other corrr functions like `rplot()`.

**Comment by BobMuenchen** [comment]
Cudos to the psych authors for adding it to corr.test.  If I had know that, I wouldn't have bothered adding it to Rcdmr. Thanks for the work-around!

**Comment by drsimonj** [comment]
Note to self, see #44

**Comment by drsimonj** [comment]
Closing as issue has been open for over 2 years
