### ISSUE TITLE
New version of / alternative to`rplot`

### ISSUE THREAD

**Issue by drsimonj** [tidymodels/corrr#35]
Below is code for a similar plot to `rplot`, but making use of `geom_tile` and `geom_text`:

```r
library(corrr)

rs <- mtcars %>% correlate() %>% rearrange(absolute = FALSE)

order <- rs %>% 
  select(-rowname) %>% 
  colnames()

rs %>% 
  stretch(na.rm = TRUE) %>%
  mutate_at(c("x", "y"), forcats::fct_relevel, ... = order) %>% 
  ggplot(aes(x, y, fill = r)) +
    geom_tile() +
    geom_text(aes(label = as.character(fashion(r))), color = "white", size = 3) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    scale_fill_gradientn(colors = c("darkred", "firebrick2", "goldenrod2", "gray", "springgreen2", "dodgerblue2", "darkblue")) +
    theme_minimal() +
    labs(x = NULL, y = NULL)
```

![new_plot](https://cloud.githubusercontent.com/assets/11235783/21164299/391decc6-c1ec-11e6-8d19-15fda84c42a0.png)

With some tweaking, it can be applied to `cord_df` after `focus`:

```r
rs <- mtcars %>% 
  correlate() %>% 
  focus(mpg:hp)

order <- rs %>% 
  select(-rowname) %>% 
  as.matrix() %>%
  #abs() %>% 
  seriation::seriate()

row_order <- rs$rowname[seriation::get_order(order, dim = 1)]
col_order <- colnames(rs[-1])[seriation::get_order(order, dim = 2)]


rs %>% 
  gather(colname, r, -rowname) %>% 
  mutate(rowname = factor(rowname, levels = row_order),
         colname = factor(colname, levels = col_order)) %>% 
  ggplot(aes(rowname, colname, fill = r)) +
  geom_tile() +
  geom_text(aes(label = as.character(corrr::fashion(r))), color = "white", size = 3) +
  scale_fill_gradientn(colors = c("darkred", "firebrick2", "goldenrod2", "gray", "springgreen2", "dodgerblue2", "darkblue"))
```

![focus_plot](https://cloud.githubusercontent.com/assets/11235783/21164467/33f7a8d0-c1ed-11e6-9a94-a1043aa28a2b.png)

**Comment by jkaupp** [comment]
I like it.  Would suggest using an outline color within `geom_tile()` with a small `width()`, either that or people can do things downstream with the plot object.  Using the `viridis` palettes  would be another option.

**Comment by drsimonj** [comment]
Thanks @jkaupp 
I've been thinking of giving the plots a bit of an overhaul to make it easier for customization like this. Not sure how soon I want to go down that path, but it's in the back of my mind!
And `viridis` is a nice idea, though I'm concerned the colours, particularly yellow, might confuse people. E.g., see [another issue](https://github.com/drsimonj/corrr/issues/39) about hot v cold. Still, there are some nice options like it :)

**Comment by drsimonj** [comment]
Closing as issue has been open for over 2 years. Can revisit code if needed.
