### ISSUE TITLE
Add citation

### ISSUE THREAD

**Issue by drsimonj** [tidymodels/corrr#47]
Add article in IBS bulletin as reference?
https://www.linkedin.com/redir/redirect?url=http%3A%2F%2Fwww%2Ebiometricsociety%2Eorg%2Fwp-content%2Fuploads%2F2016%2F12%2FIBS-Newsletter-2016_OctDec%2Epdf&urlhash=LC4u&trk=prof-publication-title-link

**Comment by edgararuiz** [comment]
I'm going to close for now, this Issue has been opened for 2 years now
