### ISSUE TITLE
Add upper triangle argument to stretch

### ISSUE THREAD

**Issue by jkeirstead** [tidymodels/corrr#57]
The package currently provides a `shave` function to convert the upper or lower triangles to `NA` values and a `stretch` function with a `na.rm` argument that lets you remove missing values.  

But what if one of the correlation pairs is undefined in the lower triangle?  A user might want to keep this entry for completeness but `stretch(..., na.rm = TRUE)` would remove it.   For example:

```
df <- data.frame(x = 1:10, y = 10:1, z = NA)
df %>% correlate() %>% shave()
```

**Comment by drsimonj** [comment]
Hi @jkeirstead. Nice idea!

Such an argument would remove the need for shave. Perhaps the extra argument could be something like `duplicates = FALSE`, which would remove one of the mirrored sides.

I'd be happy to review a pull request.
