### ISSUE TITLE
network_plot doesn't visualize the lines

### ISSUE THREAD

**Issue by Malburg** [tidymodels/corrr#63]
network_plot function from corrr package does not visualize the lines between variables (screenshot attached). Is it a bug or we're just doing it wrong?

![image](https://user-images.githubusercontent.com/41891196/43382168-9bc8e436-93df-11e8-914e-0c3cfd46d117.png)

**Comment by drsimonj** [comment]
This appears to have come up in #19 and reason there was size of the plotting panel. Can you make the panel larger or "zoom" and see if it shows?

**Comment by bhartman2** [comment]
I had the same experience.  The RStudio plotting panel will not accept resetting its size.  Apparently the function does that.

One option is as described; first zoom the panel out and you will see the lines in it.

Another option is to either open a new graphics device as a Windows window
R> windows(4,4)
and then run the plot. The lines will show there. But resizing it any way at all will cause the lines to disappear!
Alternatively, go ahead and plot in the RStudio panel without seeing the lines and then 
R> dev.copy(device=windows)
to a new windows graphics device window.  The lines will show there.

Package grDevices has a lot of methods for seeing and manipulating graphics windows on your machine.
Incidentally it allows you to create pdf or other graphics format files prior to plotting.

**Comment by edgararuiz** [comment]
Hi, is this still and issue? If so, may I get a `reprex` please?

**Comment by bhartman2** [comment]
It is still an issue wirh r 3.6 and rstudio 1.1.456.
[corrr network plot failure example.zip](https://github.com/tidymodels/corrr/files/3382927/corrr.network.plot.failure.example.zip)

**Comment by maribla22** [comment]
Hello, I had just the same problem:
![image](https://user-images.githubusercontent.com/84064788/117930713-9f5c5d80-b2fe-11eb-8417-6ba6e9db8682.png)
Where do I find a solution?
Thank you!

**Comment by tonyelhabr** [comment]
Hi @maribla22 , I was able to replicate your issue with R Gui. It seems to me that the call to `ggplot2::theme_void()` in the source for `network_plot()` is part of the problem. See [this issue](https://github.com/tidyverse/ggplot2/issues/4058#issuecomment-642223653) for more discussion.

I think the best thing to do is to use RStudio 1.4 with the `{ragg}` backend. I'm not sure how to change the graphics device backend in R Gui (which it seems that you are using), but if you use RStudio 1.4, you can find it at Tools>Options>General>Graphics.

![image](https://user-images.githubusercontent.com/15663460/118065307-563df500-b362-11eb-879c-d0b0d13742f4.png)

I ran something similar to your code in RStudio and did not have the missing arcs between labels.

```
y <- corrr::correlate(mtcars)
print(corrr::network_plot(y))
```

![image](https://user-images.githubusercontent.com/15663460/118065959-75895200-b363-11eb-89f9-9209cfd2b2d3.png)


Some other links:
+ [Hiroaki mentioned the graphic device configurability](https://twitter.com/yutannihilat_en/status/1286458090410242048) as a feature in RStudio 1.4.
+ If you want to know more about `{ragg}`, here are several good articles about it on the `{tidyverse}` site, including [this one](https://www.tidyverse.org/blog/2020/05/updates-to-ragg-and-systemfonts/).

**Comment by juliasilge** [comment]
I think this is exactly the right option; this is not a problem with corrr or even ggplot2, but with the graphics device. @maribla22 and anyone else on this older issue, if you can try out using ragg as your backend and confirm that it solves your problem, that would be great. 🙌

**Comment by maribla22** [comment]
![image](https://user-images.githubusercontent.com/84064788/118242142-48d95580-b49d-11eb-9ab6-7f5487daa412.png)
Hello,
thank you julia and tony,
I find a way to get a result to use ragg and to get an extern grafic.

**Comment by juliasilge** [comment]
Great to hear this @maribla22! Thank you so much for testing out the solution explained by @tonyelhabr. 👍
