### ISSUE TITLE
Idea for a convenience function: dice()

### ISSUE THREAD

**Issue by jameslairdsmith** [tidymodels/corrr#64]
Excellent package! 

Might be worth considering having a convenience function which wraps:

```
focus(x, ..., mirror = TRUE)
```
Where `mirror = TRUE` is pre-filled in.

I suggest `dice()` for the name of the function. The idea comes from `dplyr::slice()` which 'slices' the data frame based on the user's row selection. 'Dicing' would be the same thing, but doing so in both directions like on a chopping board.

This helped my understanding when first using the package.

I've only done a quick search, but it doesn't look like there are any obvious naming conflicts.

**Comment by edgararuiz** [comment]
Hi, I think I'm missing something here.  Wouldn't pre-selecting the rows to be "focused" on prior running the `correlate()` function do the same thing? Also, it would be computationally more efficient:

``` r
library(corrr)
library(dplyr, warn.conflicts = FALSE)

mtcars %>%
  correlate(quiet = TRUE) %>%
  focus(mpg, wt, disp, mirror = TRUE) 
#> # A tibble: 3 x 4
#>   rowname     mpg      wt    disp
#>   <chr>     <dbl>   <dbl>   <dbl>
#> 1 mpg      NA      -0.868  -0.848
#> 2 disp     -0.848   0.888  NA    
#> 3 wt       -0.868  NA       0.888

mtcars %>%
  select(mpg, wt, disp) %>%
  correlate(quiet = TRUE)
#> # A tibble: 3 x 4
#>   rowname     mpg      wt    disp
#>   <chr>     <dbl>   <dbl>   <dbl>
#> 1 mpg      NA      -0.868  -0.848
#> 2 wt       -0.868  NA       0.888
#> 3 disp     -0.848   0.888  NA
```

<sup>Created on 2019-04-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by drsimonj** [comment]
Yes, but only matters if you (a) have the unit-level data and (b) only care about the "diced" set. However, you may already have a larger correlation data frame that you're doing lots of work with, and is easier to dice than recompute all the correlations. Or, you might only have the full correlation matrix without unit-level data.
