### ISSUE TITLE
Question about reverse of stretch()

### ISSUE THREAD

**Issue by imran1570** [tidymodels/corrr#65]
I was wondering if there is a function in this package which can convert the long format of correlation data to a square correlation matrix?
In other words, the inverse/opposite of stretch().
Thanks.

**Comment by drsimonj** [comment]
No, and this would require some work to implement. It would be something along the lines of `tidyr::spread(long_dat, y, r)`, but with issues about checking compliant structure, column names (x or rowname), and ordering of columns and rows.

Anither thing to consider is whether you are intending to apply it to a long format structure created without corrr, or a long data frame created with `stretch()`.

Either way, can you give an example of when you would use such a function?

**Comment by lnalborczyk** [comment]
Hi,

thank you for writing this super useful package !

I also have the same issue/question. I have a tibble with three columns containing my first variable, my second variable, and their estimated correlation (estimate coming from from a `brmsfit` model).

For instance, let's consider the following tibble:

    tibble::tribble(
                                                  ~a,    ~b,                     ~est,
                                               "fro", "fcr",   "0.061 [-0.276, 0.38]",
                                               "fro", "nek",  "0.115 [-0.218, 0.421]",
                                               "nek", "fcr",  "0.154 [-0.169, 0.476]",
                                               "ooi", "fcr", "-0.022 [-0.352, 0.305]",
                                               "ooi", "fro",  "0.006 [-0.326, 0.323]",
                                               "ooi", "nek",  "0.173 [-0.151, 0.486]",
                                               "ooi", "zyg",   "0.039 [-0.29, 0.362]",
                                               "zyg", "fcr",  "-0.02 [-0.347, 0.317]",
                                               "zyg", "fro",  "0.092 [-0.245, 0.406]",
                                               "zyg", "nek",   "0.315 [0.011, 0.613]"
                                               )

I would like to be able to reshape this in a correlation matrix using the somehow reverse action of `corrr:stretch()`. Any idea ?

Ladislas

**Comment by edgararuiz** [comment]
Added a new `retract()` function which, I think does what you've requested:

```
corrr::retract(
  tibble::tribble(
    ~x,    ~y,     ~r,
    "fro", "ooi",   0.061,
    "fro", "nek",  0.115,
    "nek", "ooi",  0.154,
    "ooi", "ooi",  -0.022,
    "ooi", "fro",  0.006,
    "ooi", "nek",  0.173,
    "ooi", "zyg",  0.039,
    "zyg", "ooi",  -0.02,
    "zyg", "fro",  0.092,
    "zyg", "nek",  0.315
  )
)
#> # A tibble: 4 x 5
#>   rowname    ooi    fro    nek    zyg
#>   <chr>    <dbl>  <dbl>  <dbl>  <dbl>
#> 1 ooi     -0.022  0.006  0.173  0.039
#> 2 nek      0.154 NA     NA     NA    
#> 3 fro      0.061 NA      0.115 NA    
#> 4 zyg     -0.02   0.092  0.315 NA
```

**Comment by lnalborczyk** [comment]
Thank you for the follow-up!

I am not sure it does the inverse operation of stretch() however... do you know what are these NA in the resulting tibble? Should not the NA be on the diagonal? Plus, the correlation between X and Y is not the same as the correlation between Y and X...
