### ISSUE TITLE
Does corrr package can draw figure as following?

### ISSUE THREAD

**Issue by yzhlinscau** [tidymodels/corrr#77]
![s](https://user-images.githubusercontent.com/19381660/56259318-2f6e4f80-6105-11e9-815a-b4c750b3032f.png)

If possible, so what is the codes? Thanks.

**Comment by edgararuiz** [comment]
Wow, how did you create this sample plot?

**Comment by yzhlinscau** [comment]
This is a plot from one paper, they said it was plotted by corrr package. But I have no idea. So I post here.

**Comment by drsimonj** [comment]
The correlation plot (lower triangle) looks like something from the [corrplot package](https://github.com/taiyun/corrplot). I've not seen the viz of dimensions (upper triangle) like this before though. Either a new feature or something custom. Either way, not corrr. Closest thing corrr has is `rplot()` that looks a bit like the lower triangle, but not the dimension component.

**Comment by edgararuiz** [comment]
![image](https://user-images.githubusercontent.com/7875923/60937410-de01d680-a295-11e9-8861-d9a13959abc2.png)

**Comment by edgararuiz** [comment]
I'm thinking about something like that for the `autoplot()` function

**Comment by edgararuiz** [comment]
![image](https://user-images.githubusercontent.com/7875923/60971244-53e35d80-a2e9-11e9-979f-32c6057d4561.png)

**Comment by edgararuiz** [comment]
`corrplot` seems to be a good alternative: https://cran.r-project.org/web/packages/corrplot/vignettes/corrplot-intro.html
