### ISSUE TITLE
rplot() ignores rearrange() and shave()

### ISSUE THREAD

**Issue by Nick-Z0** [tidymodels/corrr#84]
Hello,

Well, the title says it all. The issue is even shown in the example [readme](https://github.com/tidymodels/corrr/blob/master/tools/readme/combination-1.png).

The thing is that it worked fine in the past as can be seen [here](https://paulvanderlaken.com/2018/09/10/simpler-correlation-analysis-in-r-using-tidyverse-principles/) and [here](https://www.datanovia.com/en/blog/easy-correlation-matrix-analysis-in-r-using-corrr-package/).

```
mtcars %>%
  corrr::correlate() %>%
  corrr::rearrange(method = "MDS", absolute = FALSE) %>%
  corrr::shave() %>%
  corrr::rplot(shape = 19, colors = c("red", "green"))
```
The plot looks like this:
![image](https://user-images.githubusercontent.com/39133010/66077004-50194d00-e55f-11e9-9a40-2249491f1ba9.png)

It should however look like this:
![image](https://user-images.githubusercontent.com/39133010/66076712-af2a9200-e55e-11e9-8d06-c707d1e008af.png)

Thanks,
Nick

P.S. The issue regarding rearrange is also open here #79.

**Comment by juliasilge** [comment]
Closed by #99
