### ISSUE TITLE
sign issues in network_plot

### ISSUE THREAD

**Issue by s-scherrer** [tidymodels/corrr#88]
If correlations are exactly zero or one, network_plot has unexpected behaviour:

* If the "correlation", or whatever users are using as measures of association is exactly 1, connecting lines will have the color corresponding to zero (white by default). This is due to setting `colour = proximity * sign` in line 227 (and line 231) of cor_df.R, where `sign` is the sign of `distance`, which is zero in this case.
When using correlation matrices this is not a problem, because both nodes will be at the same position. But when using something like Cramer's V, where two variables can be perfectly associated without having the same association values with regards to other variables, the nodes might not be at the same position. In this case the nodes are close together but no line is showing their strong association.
* If the correlation between two variables is exactly zero, `distance` will also be zero, because `sign(0) = 0` in line 189. This means the corresponding nodes will be very close together instead of far apart.

Both issues could be fixed by using `sign(rdf[row,col])` in line 211 (distance and rdf should have the same sign anyway), and setting `distance <- (1 - abs(rdf))` in line 189.
It should then also be possible to drop the `abs` around `distance` in line 192.

**Comment by topepo** [comment]
I'll be happy to make this change. Can you please provide a _minimal_ reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you! **We'll use this as a test case**

If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/tidyverse/reprex#what-is-a-reprex)", and follow the advice further down that page.

**Comment by s-scherrer** [comment]
Hi, thanks a lot for your link to reprex, pretty cool stuff!

Below are two reprexes for the two related but different issues. Please also note the linked PR which might fix the issue.

Here's a reprex for the case of perfectly uncorrelated variables:

``` r
library(corrr)

# generate correlation matrix with two perfectly uncorrelated variables
A = matrix(runif(5*5, -1, 1), ncol = 5)
C = A %*% t(A)
C[1,5] = 0
C[5,1] = 0
C = C / max(abs(C) + 0.01)
diag(C) = 1

# network_plot will (wrongly) show V1 and V5 close together, but does not show
# a line between them.
# This is because
#
#    distance = sign(rdf)(1 - abs(rdf))
#
# in network_plot, and sign(0) = 0.
# Therefore, distance = 0, and the nodes will be close together, but
# sign(distance) = 0, therefore no line is drawn.
network_plot(C, min_cor=0.1)
```

![](https://i.imgur.com/HaE7zOk.png)

<sup>Created on 2020-04-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

And here for perfectly correlated variables:

``` r
library(corrr)

# generate correlation matrix with two perfectly correlated variables,
# that don't have the same correlation with other variables
A = matrix(runif(5*5, -1, 1), ncol = 5)
C = A %*% t(A)
C = C / max(abs(C) + 0.01)
C[1,5] = 1
C[5,1] = 1
diag(C) = 1

# network_plot will (correctly) show V1 and V5 close together, but not at the same
# location, because the distances to the other variables are not the same.
#
# However, network_plot does not show a colored connection between V1 and
# V5.
network_plot(C, min_cor=0.1)
```

![](https://i.imgur.com/j0OwbT9.png)

<sup>Created on 2020-04-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
