### ISSUE TITLE
Support for arbitrary functions

### ISSUE THREAD

**Issue by jameslairdsmith** [tidymodels/corrr#94]
I've really enjoyed using `corrr`; it is an excellent package! Thanks for all the great work! One thing that I think would make it even more useful would be if there was support for arbitrary functions. At the moment we are limited to only creating dataframes of correlations (of various types). That's useful, but there are a number of different kind of pairwise statistics that can be calculated for the variables of a dataframe. I can see on a separate issue (#42) there has been a request for covariance to also be supported.

But it seems a more robust and elegant solution would be to have a function that could take an arbitrary function. And would return a `cor_df` like object, but with values output from that arbitrary function rather than correlations. There would have to be a few changes, like those already mentioned in the covariance issue. Not all outputs would be on a scale from -1 to 1 for example.

A relatively simple example would be a linear regression using `lm()`. If there were this form of the `correlate()` function, it could make the arbitrary function output the beta from regressing each of the variables onto one another. (The beta of regressing y on x is not the same as regressing x on y, so there wouldn't be duplication like in the case of correlations). If you wanted to find the p-values of those regressions, you could simply change the arbitrary function to output the p-values instead. Same thing if you wanted the R^2.

**Comment by topepo** [comment]
I think that the solution here would be to make new S3 methods for `correlate()`. Would you like to make a pull request for some? 

I like the idea of linear model covariance matrices here but we have to make sure that there is not problematic amounts of feature-creep.

**Comment by Athospd** [comment]
That would be a powerful feature! Make sense wide this idea for categorical features as well? For instance, a Cramer's V or Chisq matrix.

(actually it makes me imagine a list-matrix, a 2D version of list columns =P)

**Comment by juliasilge** [comment]
Closed in #116!!! 🚀
